apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: llm-chat-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: a simple chatbot GUI that responds to user input with a random message from a list of pre-determind responses.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'