metadata:
  name: llm-chat-app
  namespace: llm-chat-app
  labels:
    app.kubernetes.io/component: llm-chat-app
    app.kubernetes.io/name: llm-chat-app
    app.kubernetes.io/part-of: llm-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-chat-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-chat-app
    spec:
      initContainers:
      containers:
        - name: llm-chat-app
          env:
          image: docker.io/neerajtiwari/llm-chat-app:latest
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 20m
              memory: 256Mi
