apiVersion: v1
kind: Service
metadata:
  name: llm-chat-app
  namespace: llm-chat-app
  labels:
    app.kubernetes.io/component: llm-chat-app
    app.kubernetes.io/name: llm-chat-app
    app.kubernetes.io/part-of: llm-chat-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  selector:
    app.kubernetes.io/name: llm-chat-app
